name: nocd
description: An OCD treatment app.
version: 1.0.0+1

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  rxdart: ^0.22.6
  http: ^0.12.0+2
  dio: ^2.1.16
  flushbar: ^1.9.1
  sentry: ^2.3.1
  provider: ^3.1.0+1
  flutter_animation_progress_bar: ^1.0.0
  auto_size_text: ^2.1.0
  shimmer: ^1.0.1
  flutter_bloc: ^2.0.0
  equatable: ^0.6.1
  flutter_linkify: ^2.1.0
  like_button: ^0.1.9
  flutter_html: ^0.11.0
  flutter_pubnub: ^0.2.0
  uuid: 2.0.2
  intl: ^0.16.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/ralert/
  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/fonts/product_sans_regular.ttf
        - asset: assets/fonts/product_sans_bold.ttf
          weight: 700
  module:
    androidX: true
    androidPackage: com.treatmyocd.nocd.flutter
    iosBundleIdentifier: com.treatmyocd.nocd-dev
